DEEPSORT:
  REID_CKPT: "deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  # extractor parameters
  name_extractor: "osnet_x1_0"
  #["basic_net", "osnet_x1_0", "osnet_x0_75", "osnet_x0_5", "osnet_x0_25"]
  
